# Generated by Django 5.2.6 on 2025-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('client', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('client_kk', models.CharField(max_length=255, null=True, verbose_name='Заказчик')),
                ('client_ru', models.CharField(max_length=255, null=True, verbose_name='Заказчик')),
                ('client_en', models.CharField(max_length=255, null=True, verbose_name='Заказчик')),
                ('category', models.CharField(choices=[('state-social', 'Гос. соц. заказ'), ('state-grant', 'Грант'), ('charity', 'Благотворительная помощь')], max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
                ('role_kk', models.CharField(max_length=100, null=True, verbose_name='Роль')),
                ('role_ru', models.CharField(max_length=100, null=True, verbose_name='Роль')),
                ('role_en', models.CharField(max_length=100, null=True, verbose_name='Роль')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
    ]
