"""
Django settings for jbomangystau project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from decouple import config

# --- BASE DIR ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY ---
SECRET_KEY = 'django-insecure-6qjuj&1_x&$9)5vziuxqdo#_j0g!g@7bq^3p-=uz%1fn#_vm_s'
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok-free.app']

# --- APPLICATIONS ---
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'main',  # ваше приложение
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # для мультиязычности
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- URLS & WSGI ---
ROOT_URLCONF = 'jbomangystau.urls'
WSGI_APPLICATION = 'jbomangystau.wsgi.application'

# --- TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # общая папка шаблонов
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # поддержка i18n в шаблонах
            ],
        },
    },
]

# --- DATABASE ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = 'ru'  # язык по умолчанию

LANGUAGES = [
    ('kk', 'Қазақша'),
    ('ru', 'Русский'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# --- STATIC FILES ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "main/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- EMAIL SETTINGS ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mangystau.bastama@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'mangystau.bastama@gmail.com'

# --- MESSAGE STORAGE ---
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# --- DEFAULT PRIMARY KEY FIELD TYPE ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- MEDIA FILES ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]

# Jazzmin настройки
JAZZMIN_SETTINGS = {
    # 🔹 Заголовки и бренд
    "site_title": "ЦМИ Мангистау | Админ",
    "site_header": "ЦМИ Мангистау",
    "site_brand": "Админ-панель",
    "welcome_sign": "Добро пожаловать 👋 в панель управления",
    "site_logo": "main/img/logo.png",   # путь к твоему лого (положи в static)
    "site_logo_classes": "img-circle",  # сделает логотип круглым
    "site_icon": "main/img/favicon.ico",

    # 🔹 Темы (Bootstrap + dark mode)
    "theme": "darkly",              # тёмная тема по умолчанию
    "dark_mode_theme": "cyborg",    # если у пользователя включена тёмная тема

    # 🔹 Навигация
    "show_sidebar": True,
    "navigation_expanded": True,  # меню открыто по умолчанию
    "hide_apps": [],              # можешь скрыть ненужные приложения
    "hide_models": [],

    # 🔹 Иконки моделей (Font Awesome)
    "icons": {
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "main.Project": "fas fa-briefcase",
        "main.Service": "fas fa-tools",
        "main.TeamMember": "fas fa-user-tie",
    },

    # 🔹 Порядок отображения приложений
    "order_with_respect_to": ["auth", "main"],

    # 🔹 Нижний колонтитул
    "copyright": "© ЦМИ Мангистау 2025",
}